base_url = "https://tjmaynes.com"
title = "TJ Maynes"
description = "A development blog focused on Rust and mobile development."

generate_feed = true

compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "solarized-light"
render_emoji = true