name: CI

on:
  push:
    branches:
      - main

jobs:
  ship_it:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v1
      - name: 🔨 Install Dependencies 🔨
        run: sudo apt-get update && sudo apt-get install make
      - name: 🧪 Build Website 🧪
        run: make artifact         
      - name: 🚀 Deploy Website 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
