name: CI

on:
  push:
    branches:
      - main

jobs:
  ship_it:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 🔨 Install Dependencies 🔨
        run: sudo apt-get update && sudo apt-get install make
      - name: 🧪 Build Website 🧪
        run: make artifact
      - name: 🚀 Deploy Website 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
