name: CI

on:
  push:
    branches:
      - main

jobs:
  ship_it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 🔨 Install Dependencies 🔨
        run: sudo apt-get update && sudo apt-get install make
      - name: 🧪 Build Website 🧪
        run: make artifact
      - name: 🚀 Deploy Website 🚀
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tjmaynes.com
          directory: public/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
