name: CI
on: [push]
jobs:
  ship_it:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: 🧪 Build for Deployment 🧪
        run: nix-shell --run "make build_for_deployment"
      - name: 🚀 Deploy Website 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site 
          CLEAN: true
